services:
  app:
    restart: always
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    ports:
      - 3000:3000

  mongo:
    restart: always
    image: mongo:7.0.14-jammy
    volumes:
      - mongo_data:/data/db
    expose:
      - 27017
  
volumes:
  mongo_data: